name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build -t raja1111/web2-server:latest ./backend

      - name: Publish Image to Docker Hub
        run: docker push raja1111/web2-server:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull raja1111/web2-server:latest

      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name new-web2-server-container \
            -e GOOGLE_API_KEY='${{secrets.GOOGLE_API_KEY}}' \
            -e ACCOUNTSID='${{secrets.TWILIO_ACCOUNT_SID}}' \
            -e AUTHTOKEN='${{secrets.TWILIO_AUTH_TOKEN}}' \
            -e MONGOURI='${{secrets.MONGOURI}}' \
            -e WEB1_MONGOURI='${{secrets.WEB1_MONGOURI}}' \
            -e email='${{secrets.email}}' \
            -e password='${{secrets.password}}' \
            raja1111/web2-server:latest
