name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t raja1111/web2-server ./backend./Dockerfile
      - name: Publish Image to docker hub
        run: docker push raja1111/web2-server:latest  
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from docker hub
        run: docker pull raja1111/web2-server:latest
      - name: Run Docker Container 
        run: docker run -d -p 5000:5000 --name web2-server-container raja1111/web2-server
